name: Deployment pipeline

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: registry.carp.dk
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      run: |
        docker build -t registry.carp.dk/carp/carp-app-site:latest .
        docker push registry.carp.dk/carp/carp-app-site:latest
    
    - name: Redeploy stack
      uses:  manicmade/portainer-git-stack-redeploy-action@v1.5.3
      with:
        portainerUrl: 'https://dev.carp.dk/portainer'
        accessToken: '${{ secrets.PORTAINER_API_KEY }}'
        stackName: 'app-site-stack'
        branch: 'refs/heads/main'
        